name: flutter_application_1
description: 'PlanMyWedding App'
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  path_provider: ^2.1.2
  share_plus: ^7.2.1
  pdf: ^3.10.7
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/categories/
    # category images
    - assets/images/categories/accessories.png
    - assets/images/categories/cake.png
    - assets/images/categories/car_rental.png
    - assets/images/categories/card_printing.png
    - assets/images/categories/catering.png
    - assets/images/categories/decor_lighting.png
    - assets/images/categories/flower_shops.png
    - assets/images/categories/gifts.png
    - assets/images/categories/music.png
    - assets/images/categories/photographers.png
    - assets/images/categories/venues.png
    - assets/images/categories/wedding_planner.png

    # existing images
    - assets/images/classic.png
    - assets/images/classic1.png
    - assets/images/classic2.png
    - assets/images/minimal.png
    - assets/images/minimal1.png
    - assets/images/botanical.png
    - assets/images/botanical1.png
    - assets/images/romantic.png
    - assets/images/romantic1.png
    - assets/images/romantic2.png
    - assets/images/table.png
    - assets/images/become_provider.png

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
